### ISSUE TITLE
Color and style problems

### ISSUE THREAD

**Issue by jEsuSdA** [PapirusDevelopmentTeam/papirus-amule-theme#1]
Hi!

Great theme, but I have some problems when using it with Greybird (or another light theme):

![screenshot63](https://user-images.githubusercontent.com/5833446/30002097-405321d0-90a1-11e7-88d9-3a9c7c44d45e.png)

As you can see, the IMPORT icon is "invisible" cause its gray main color.

Another suggestions:

* ¿Why the search button is green when the Papirus theme for search tools is blue? Blue looks like much better and has a direct relation with the Papirus theme. ;)

![screenshot64](https://user-images.githubusercontent.com/5833446/30002118-c2dbe7e0-90a1-11e7-9dce-29d6c4f1b429.png)

* The DOWNLOADS icon has a strong border that breaks the Papirus style. By other hand, and more important, the DOWNLOAD aMule tab is ONLY for Downloads, so, the Up-arrow have no much sense. A Down-arrow only symbol is better.

In fact, In my proposal, I used the Download Folder icon (for downloads) and the Public Folder icon for (for uploads) cause they have more sense and have relation with the general download-upload actions.

* And a last suggestion. I do not consider a concept error to use the "GEAR" icon for Options. In fact it is a great idea. But the aMule options window is so big and has a lot of configuration options, so, I associate it to a "Control Panel", so, I suggest using the Papirus "Control Panel" icon. What do you think about?

![screenshot65](https://user-images.githubusercontent.com/5833446/30002156-a8a632d0-90a2-11e7-8790-fd8ce3f7d9f5.png)

**Comment by varlesh** [comment]
@jEsuSdA We use `#cccccc` color for **white** color. Your GTK theme use gradient  and similar with icon color. I think better soloution - change GTK Theme, because  `#cccccc` color use on more apps.
Also not forgot, we adapt icons for Arc-Light, Arc-Dark and eOS only!!!

I combine colors for toolbar, because i don't like more blue icons .... It's looking not good.

> The DOWNLOADS icon has a strong border that breaks the Papirus style.

No. Open apps and see, more icons use this style. Also see gnome (or default) skin icon - it's icon similar.

> And a last suggestion. I do not consider a concept error to use the "GEAR" icon for Options. In fact it is a great idea. But the aMule options window is so big and has a lot of configuration options, so, I associate it to a "Control Panel", so, I suggest using the Papirus "Control Panel" icon. What do you think about?

No. Сurrent icon looking better (see my previos comment about combine colors)

**Comment by varlesh** [comment]
Arc Light:
![image](https://user-images.githubusercontent.com/8083855/30002423-279e89ae-90ba-11e7-8037-d461466a03c9.png)
Arc Dark on readme

**Comment by varlesh** [comment]
We not adapt Papirus for Ambiance, Breeze, Adwaita, Elementary-XFCE and more 1000000 other DE-Themes, because it's impossible!!!

**Comment by varlesh** [comment]
@jEsuSdA You can change not like colors on any text editor and build for your GTK-Theme.
It's easy :) Closed

**Comment by jEsuSdA** [comment]
Ok, I understand.

I still prefering Greybird. I don't like Arc cause are "so plane" and "so bright / dark" for me... I prefer a more neutral theme.  In addition, I read you post Arc appears to be not totally mantained whereas Greybird has a good support. ;)

I'll create a mixed aMule theme to solve all these problems. ;)

Thank you so much! ;)
