### ISSUE TITLE
Problems with installation Papirus-amule-Theme

### ISSUE THREAD

**Issue by IvanDeFelice76** [PapirusDevelopmentTeam/papirus-amule-theme#3]
papirus-amule-theme]$ make build
rm -rf ./build
rm -f Papirus-Adapta.zip ePapirus.zip Papirus-Dark.zip Papirus-Adapta-Nokto.zip Papirus.zip
sh ./src/_convert-to-png.sh
=> Generate bitmap icons ...
Convert ./src/./Papirus-Adapta-Nokto/Client_A4AFNoNeededPartsQueueFull.svg -> ./src/../build/Papirus-Adapta-Nokto/Client_A4AFNoNeededPartsQueueFull.png
./src/_convert-to-png.sh: riga 20: rsvg-convert: comando non trovato
make: *** [Makefile:19: convert] Error 127
[xzj8b3@x555lp papirus-amule-theme]$ sudo make build
rProblems with Fedora 28 64 bit The theme is not possible to install

m -rf ./build
rm -f Papirus-Adapta.zip ePapirus.zip Papirus-Dark.zip Papirus-Adapta-Nokto.zip Papirus.zip
sh ./src/_convert-to-png.sh
=> Generate bitmap icons ...
Convert ./src/./Papirus-Adapta-Nokto/Client_A4AFNoNeededPartsQueueFull.svg -> ./src/../build/Papirus-Adapta-Nokto/Client_A4AFNoNeededPartsQueueFull.png
./src/_convert-to-png.sh: riga 20: rsvg-convert: comando non trovato
make: *** [Makefile:19: convert] Error 127

**Comment by SmartFinn** [comment]
> ./src/_convert-to-png.sh: riga 20: rsvg-convert: comando non trovato

At first, install all needed dependencies https://github.com/PapirusDevelopmentTeam/papirus-amule-theme#manual-install

The name of packages may differ.

**Comment by IvanDeFelice76** [comment]
Nessuna corrispondenza per l'argomento: librsvg2-bin
Looks like that macaque!!!

**Comment by SmartFinn** [comment]
@xzj8b3 try to install `librsvg2-tools` instead.

**Comment by IvanDeFelice76** [comment]
It is not very much use Fedora.... however beautiful, but lacks a package for qbittorrent to complete the work... also because Papirus remains the most complete and stable theme!!!!

**Comment by twotalks** [comment]
Can't install any dependencies. home-brew code give me an error.
